LoLChamps:
- macros:
  - brightness: 80
    color: 5;0;163
    fadein: 200
    fadeout: 200
    key: q
    keycode: 113
  - brightness: 80
    color: 5;0;163
    fadein: 200
    fadeout: 200
    key: w
    keycode: 114
  name: Blitzcrank
Macros:
- brightness: 100
  color: 240;224;254
  fadein: 2550
  fadeout: 1
  id: 1586796485294
  key: k
  keycode: 107
  name: r
- brightness: 100
  color: 254;25;0
  fadein: 2550
  fadeout: 7
  id: 1586796521712
  key: w
  keycode: 119
  name: w
- brightness: 100
  color: 254;25;0
  fadein: 2550
  fadeout: 10
  id: 1586796536218
  key: e
  keycode: 101
  name: e
- brightness: 60
  color: 91;22;10
  fadein: 2550
  fadeout: 1
  id: 1586801211192
  key: q
  keycode: 113
  name: k
Serial:
  BaudRate: 115200
  Port: COM6
