Macros:
- brightness: 70
  color: '#fff0cf'
  fadein: 1000
  fadeout: 100000
  key: KeyS
  name: Test 1
- brightness: 100
  color: '#ffffff'
  fadein: 10
  fadeout: 10
  key: KeyS
  name: sda
- brightness: 100
  color: '#ffffff'
  fadein: 10
  fadeout: 10
  key: KeyQ
  name: sdasd
- brightness: 100
  color: '#ffffff'
  fadein: 10
  fadeout: 10
  key: KeyN
  keycode: 78
  name: pippo
- brightness: 100
  color: '#ffffff'
  fadein: 10
  fadeout: 10
  key: KeyN
  keycode: 78
  name: wefwerfwef
- brightness: 100
  color: '#ffffff'
  fadein: 10
  fadeout: 10
  key: KeyC
  keycode: 67
  name: dioporco
Serial:
  BaudRate: 115200
  Port: COM5
