Macros:
- brightness: 100
  color: FF0000
  fadein: 50
  fadeout: 50
  key: Q
  name: macro 1
- brightness: 100
  color: FF0000
  fadein: 50
  fadeout: 50
  key: W
  name: macro 2
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 10
  key: KeyV
  name: pippo
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 10
  key: KeyT
  name: dtrhethrteh
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 10
  key: KeyU
  name: pluto
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 60
  key: KeyM
  name: wedf
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 10
  key: KeyZ
  name: hello
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 10
  key: KeyM
  name: hello
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 10
  key: KeyM
  name: hello
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 10
  key: KeyM
  name: hello
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 10
  key: KeyM
  name: hello
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 10
  key: KeyM
  name: hello
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 10
  key: KeyM
  name: hello
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 10
  key: KeyM
  name: hello
- brightness: 200
  color: rgb(0,0,0)
  fadein: 10
  fadeout: 10
  key: KeyM
  name: hello
