LoLChamps:
- macros:
  - brightness: 80
    color: 5;0;163
    fadein: 200
    fadeout: 200
    key: q
    keycode: 113
  - brightness: 80
    color: 5;0;163
    fadein: 200
    fadeout: 200
    key: w
    keycode: 114
  name: Blitzcrank
Macros:
- brightness: 100
  color: 245;254;254
  fadein: 60
  fadeout: 70
  id: 1586373124614
  key: q
  keycode: 113
  name: verde
Serial:
  BaudRate: 921600
  Port: COM11
