Macros:
- brightness: 100
  color: 254;0;13
  fadein: 200
  fadeout: 200
  id: 1586372566931
  key: KeyG
  keycode: 103
  name: blu
- brightness: 86
  color: 18;188;0
  fadein: 60
  fadeout: 70
  id: 1586373124614
  key: KeyM
  keycode: 109
  name: fgefgerfg
Serial:
  BaudRate: 115200
  Port: COM5
