LoLChamps:
- macros:
  - brightness: 80
    color: 5;0;163
    fadein: 200
    fadeout: 200
    key: q
    keycode: 113
  - brightness: 80
    color: 5;0;163
    fadein: 200
    fadeout: 200
    key: w
    keycode: 114
  name: Blitzcrank
Macros:
- brightness: 70
  color: 125;62;0
  fadein: 1000
  fadeout: 1000
  id: 1586796485294
  key: d
  keycode: 100
  name: Flash
- brightness: 70
  color: 0;67;125
  fadein: 500
  fadeout: 500
  id: 1586796521712
  key: a
  keycode: 97
  name: A i u t o o
- brightness: 70
  color: 125;62;0
  fadein: 300
  fadeout: 300
  id: 1586796536218
  key: n
  keycode: 110
  name: Missing
- brightness: 60
  color: 91;3;0
  fadein: 300
  fadeout: 300
  id: 1586801211192
  key: m
  keycode: 109
  name: Vision
Serial:
  BaudRate: 115200
  Port: COM7
